### ISSUE TITLE
smart-proxy crashes after a while

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-smart-proxy#48]
smart proxy crashes after around a minute of work with the following error:
```
{"level":"info","time":"2020-06-24T06:39:29Z","message":"Starting HTTP server at ':8080'"}
{"level":"info","time":"2020-06-24T06:39:29Z","message":"Initializing HTTP server at ':8080'"}
{"level":"info","time":"2020-06-24T06:39:29Z","message":"Updating groups information"}
{"level":"info","time":"2020-06-24T06:39:29Z","message":"getting rules static content"}
{"level":"debug","time":"2020-06-24T06:39:29Z","message":"Connecting to http://ccx-insights-content-service:8080/api/v1/content "}
{"level":"debug","time":"2020-06-24T06:39:29Z","message":"Connecting to http://ccx-insights-content-service:8080/api/v1/groups "}
{"level":"info","time":"2020-06-24T06:39:29Z","message":"Received 4 groups"}
{"level":"info","time":"2020-06-24T06:39:29Z","message":"Updating groups configuration each 60.000000 seconds"}
{"level":"error","time":"2020-06-24T06:39:29Z","message":"invalid to parse time \"2020-02-07 14:19:00\" using layout \"2006-01-02T15:04:05Z07:00\""}
{"level":"info","time":"2020-06-24T06:39:37Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:39:43Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:39:47Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:39:53Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:39:57Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:03Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:07Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:13Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:17Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:23Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:27Z","message":"Request received - URI: /api/insights-results-aggregator/v1/openapi.json, Method: GET"}
{"level":"info","time":"2020-06-24T06:40:29Z","message":"getting rules static content"}
{"level":"debug","time":"2020-06-24T06:40:29Z","message":"Connecting to http://ccx-insights-content-service:8080/api/v1/content "}
{"level":"error","time":"2020-06-24T06:40:29Z","message":"invalid to parse time \"2019-10-29 15:00:00\" using layout \"2006-01-02T15:04:05Z07:00\""}
panic: close of closed channel

goroutine 12 [running]:
github.com/RedHatInsights/insights-results-smart-proxy/content.updateContent(0xc00002c033, 0x4b, 0xc00002a030, 0x30, 0xdf8475800)
	/opt/app-root/src/content/content.go:155 +0x103
github.com/RedHatInsights/insights-results-smart-proxy/content.RunUpdateContentLoop(0xc00002c033, 0x4b, 0xc00002a030, 0x30, 0xdf8475800)
	/opt/app-root/src/content/content.go:139 +0x57
created by main.startServer
	/opt/app-root/src/smart_proxy.go:101 +0x240
```

**Comment by bond95** [comment]
Same error while running unit tests:
```
./build.sh
./unit-tests.sh
ok  	github.com/RedHatInsights/insights-results-smart-proxy	30.265s	coverage: 47.1% of statements
ok  	github.com/RedHatInsights/insights-results-smart-proxy/conf	0.169s	coverage: 84.6% of statements
?   	github.com/RedHatInsights/insights-results-smart-proxy/content	[no test files]
{"level":"error","error":"listen tcp: address 99999: invalid port","time":"2020-06-24T09:05:59+02:00","message":"Unable to start HTTP/S server"}
panic: close of closed channel

goroutine 70 [running]:
github.com/RedHatInsights/insights-results-smart-proxy/content.updateContent(0x48a78a1, 0x16, 0x48a78b7, 0x16, 0xdf8475800)
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/content/content.go:155 +0x103
github.com/RedHatInsights/insights-results-smart-proxy/content.RunUpdateContentLoop(0x48a78a1, 0x16, 0x48a78b7, 0x16, 0xdf8475800)
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/content/content.go:139 +0x57
created by github.com/RedHatInsights/insights-results-smart-proxy/server_test.TestHTTPServer_ClusterReportEndpoint.func1
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/server/server_test.go:236 +0x31e
FAIL	github.com/RedHatInsights/insights-results-smart-proxy/server	0.236s
?   	github.com/RedHatInsights/insights-results-smart-proxy/services	[no test files]
?   	github.com/RedHatInsights/insights-results-smart-proxy/types	[no test files]
FAIL
unit tests failed
make: *** [test] Error 1
```

**Comment by tisnik** [comment]
`panic: close of closed channel` seems like race condition rather. @Sergey1011010 pls. look at timeouts etc. in unit tests
