### ISSUE TITLE
99999: invalid port

### ISSUE THREAD

**Issue by bond95** [RedHatInsights/insights-results-smart-proxy#58]
Got error while running unit tests:
```
./build.sh
./unit-tests.sh
ok  	github.com/RedHatInsights/insights-results-smart-proxy	30.265s	coverage: 47.1% of statements
ok  	github.com/RedHatInsights/insights-results-smart-proxy/conf	0.169s	coverage: 84.6% of statements
?   	github.com/RedHatInsights/insights-results-smart-proxy/content	[no test files]
{"level":"error","error":"listen tcp: address 99999: invalid port","time":"2020-06-24T09:05:59+02:00","message":"Unable to start HTTP/S server"}
panic: close of closed channel

goroutine 70 [running]:
github.com/RedHatInsights/insights-results-smart-proxy/content.updateContent(0x48a78a1, 0x16, 0x48a78b7, 0x16, 0xdf8475800)
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/content/content.go:155 +0x103
github.com/RedHatInsights/insights-results-smart-proxy/content.RunUpdateContentLoop(0x48a78a1, 0x16, 0x48a78b7, 0x16, 0xdf8475800)
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/content/content.go:139 +0x57
created by github.com/RedHatInsights/insights-results-smart-proxy/server_test.TestHTTPServer_ClusterReportEndpoint.func1
	/Users/bohdan/go/src/github.com/redhatinsights/insights-results-smart-proxy/server/server_test.go:236 +0x31e
FAIL	github.com/RedHatInsights/insights-results-smart-proxy/server	0.236s
?   	github.com/RedHatInsights/insights-results-smart-proxy/services	[no test files]
?   	github.com/RedHatInsights/insights-results-smart-proxy/types	[no test files]
FAIL
unit tests failed
make: *** [test] Error 1
```

_Originally posted by @bond95 in https://github.com/RedHatInsights/insights-results-smart-proxy/issues/48#issuecomment-648636734_

**Comment by joselsegura** [comment]
The invalid port error is completely normal.

During the unit tests, one of them is testing that trying to configure a bad port number results in a failing server. When other test fails, all the error logs for the server_test package are shown and this one is printed, but it's not a real problem, only the log message generated by the library in response to a previous test case.
