### ISSUE TITLE
Unexpected failure when `auth` is set to `False`

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-smart-proxy#737]
```
9:08AM INF Request received - URI: /api/v1/clusters/00000000-1111-2222-3333-444444444444/report, Method: GET
9:08AM ERR handleServerError() error="token is not provided"
9:08AM INF Cluster ID: 00000000-1111-2222-3333-444444444444; get_disabled flag = false
9:08AM INF Cluster ID: 00000000-1111-2222-3333-444444444444; osd_eligible flag = false
2021/12/07 09:08:13 http: panic serving 127.0.0.1:59118: runtime error: invalid memory address or nil pointer dereference
goroutine 90 [running]:
net/http.(*conn).serve.func1()
        /opt/go/src/net/http/server.go:1801 +0xb9
panic({0xff48a0, 0x1aa98b0})
        /opt/go/src/runtime/panic.go:1047 +0x266
github.com/RedHatInsights/insights-results-smart-proxy/server.HTTPServer.reportEndpoint({{{0xc000399058, 0x5}, {0xc000399090, 0x9}, {0xc0003990c8, 0x8}, {0xc0003990f8, 0x8}, {0xc000041360, 0x1a}, ...}, ...}, ...)
        /home/ptisnovs/ccx/insights-results-smart-proxy/server/server.go:712 +0x36d
net/http.HandlerFunc.ServeHTTP(0x1005020, {0x1333378, 0xc000395660}, 0x8)
        /opt/go/src/net/http/server.go:2046 +0x2f
github.com/RedHatInsights/insights-operator-utils/http.logRequestHandler({0x1333f48, 0xc0003660e0}, 0xc0007ec300, {0x1327b20, 0xc0000ddd40})
        /home/ptisnovs/go/pkg/mod/github.com/!red!hat!insights/insights-operator-utils@v1.22.0/http/metrics_middleware.go:56 +0x2a2
github.com/RedHatInsights/insights-operator-utils/http.LogRequest.func1({0x1333f48, 0xc0003660e0}, 0xc000261890)
        /home/ptisnovs/go/pkg/mod/github.com/!red!hat!insights/insights-operator-utils@v1.22.0/http/metrics_middleware.go:68 +0x2b
net/http.HandlerFunc.ServeHTTP(0xc0007ec200, {0x1333f48, 0xc0003660e0}, 0xc0001259f8)
        /opt/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0007c6c00, {0x1333f48, 0xc0003660e0}, 0xc0007ec100)
        /home/ptisnovs/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc0002616b0}, {0x1333f48, 0xc0003660e0}, 0xc0007ec100)
        /opt/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0000db4a0, {0x133c3f8, 0xc000261560})
        /opt/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:3033 +0x4e8
```

**Comment by dpensi** [comment]
This bug was fixed previously by Dbily on this previous commit: https://github.com/RedHatInsights/insights-results-smart-proxy/commit/e67f1452c172a0909631fb4c569faf52001000dc

Closing
